[http.middlewares]
  [http.middlewares.redirect-https.redirectScheme]
    scheme = "http"

[http.routers]
    [http.routers.redirs]
        rule = "HostRegexp(`{host:.+}`)"
        entrypoints = ["http"]
        middlewares = ["redirect-https"]
        service = "noop"

[http.services]
    # noop service, the URL will be never called
    [http.services.noop.loadBalancer]
        [[http.services.noop.loadBalancer.servers]]
            url = "http://172.19.0.1"  # My router
